### ISSUE TITLE
Vibrator - noise

### ISSUE THREAD

**Issue by Rekonin** [dukesrg/logue-fx#4]
I'm getting quite a bit of noise/crackle and some glitching from Vibrator.
Tried all three versions and it's consistent.
Recorded a sample for you: https://filebin.net/6vahgpd1rboqg6br (link only active for 6 days, so I can upload again if you don't see this in time)
I tested the other FX and it also seems to happen, but much less, with Hyper

**Comment by dukesrg** [comment]
That's by implementation as it does a circular bufer with different playback speed. Sooner o later underflow/overflow occurs and the next sample will have an audible step. The smaller detune is the more rare this happens, but it is inevitable with such implementation, sorry.

**Comment by Rekonin** [comment]
Honestly the glitch part is actually sorta fine, I kinda like it. It's the constant high-freq static noise that's the bummer

**Comment by dukesrg** [comment]
Well, technically it is possible to alter the noise character with adjusting the circular buffer size - the frequency of the over/underruns will be changed such a way.

**Comment by Rekonin** [comment]
Explanation received from repo owner
